# -*- coding: utf-8 -*-
"""optimization_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ctobWxdyO3hdq84cFjdzvp5zMDAmiyzT
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import gurobipy as gp
import numpy as np
import pandas as pd
from gurobipy import GRB


@dataclass
class ModelConfig:
    """
    Configuration for the NFL constrained minimum dominating set model.

    radius_miles:
        Maximum distance for one selected city to 'cover' another city.

    mip_gap:
        Acceptable optimality gap for Gurobi.

    time_limit:
        Solver time limit in seconds.

    global_budget_factor:
        If no explicit budget is supplied, budget is computed as:
        global_budget_factor * sum(candidate_city_costs)

    separation_pairs:
        Optional pairs of row indices that cannot both be selected.
        Example: [(0, 1), (5, 12)]
    """

    radius_miles: float = 250.0
    mip_gap: float = 0.0
    time_limit: int | None = 300
    global_budget_factor: float = 0.40
    separation_pairs: list[tuple[int, int]] | None = None


class NFLExpansionOptimizer:
    """
    Reusable optimizer for the NFL expansion problem.

    This class does 4 main things:
    1. Cleans and validates the input data
    2. Builds the coverage adjacency matrix
    3. Solves the optimization model
    4. Runs sensitivity sweeps over population and economic thresholds
    """

    def __init__(
        self,
        df: pd.DataFrame,
        city_id_col: str = "City",
        latitude_col: str = "Latitude_num",
        longitude_col: str = "Longitude_num",
        budget_col: str = "Budget_num",
        phi_prefixes: Iterable[str] = ("φ", "phi"),
        theta_prefixes: Iterable[str] = ("θ", "theta"),
        config: ModelConfig | None = None,
    ) -> None:
        self.df = df.copy()
        self.city_id_col = city_id_col
        self.latitude_col = latitude_col
        self.longitude_col = longitude_col
        self.budget_col = budget_col
        self.phi_prefixes = tuple(p.lower() for p in phi_prefixes)
        self.theta_prefixes = tuple(p.lower() for p in theta_prefixes)
        self.config = config or ModelConfig()

        self._clean_columns()
        self._validate_required_columns()

        self.n = len(self.df)
        self.city_ids = self.df[self.city_id_col].astype(str).tolist()
        self.latitudes = pd.to_numeric(self.df[self.latitude_col], errors="coerce").to_numpy()
        self.longitudes = pd.to_numeric(self.df[self.longitude_col], errors="coerce").to_numpy()
        self.costs = self._build_cost_vector()

        self.phi_cols = self._find_prefixed_columns(self.phi_prefixes)
        self.theta_cols = self._find_prefixed_columns(self.theta_prefixes)

        self._validate_coordinates()

    def _clean_columns(self) -> None:
        """
        Standardizes column names by trimming whitespace.
        """
        self.df.columns = [str(c).strip() for c in self.df.columns]

    def _validate_required_columns(self) -> None:
        """
        Ensures the core columns exist before we do any modeling.
        """
        required = [self.city_id_col, self.latitude_col, self.longitude_col]
        missing = [c for c in required if c not in self.df.columns]
        if missing:
            raise ValueError(f"Missing required columns: {missing}")

    def _build_cost_vector(self) -> np.ndarray:
        """
        Builds the city cost vector.

        If the budget column is missing, every city gets cost = 1.
        """
        if self.budget_col in self.df.columns:
            return pd.to_numeric(self.df[self.budget_col], errors="coerce").fillna(1.0).to_numpy()
        return np.ones(len(self.df), dtype=float)

    def _find_prefixed_columns(self, prefixes: tuple[str, ...]) -> list[str]:
        """
        Finds all columns whose names begin with one of the supplied prefixes.

        Example:
            prefixes = ("phi", "φ")
            Matches: phi_1, phi_2, φ1, φ_market
        """
        cols: list[str] = []
        for col in self.df.columns:
            col_lower = col.lower()
            if any(col_lower.startswith(prefix) for prefix in prefixes):
                cols.append(col)
        return cols

    def _validate_coordinates(self) -> None:
        """
        Makes sure every row has usable latitude and longitude values.
        """
        bad_coords = np.isnan(self.latitudes) | np.isnan(self.longitudes)
        if bad_coords.any():
            bad_rows = self.df.loc[bad_coords, [self.city_id_col, self.latitude_col, self.longitude_col]]
            raise ValueError(
                "Some rows have invalid coordinates.\n"
                f"Problem rows:\n{bad_rows.to_string(index=False)}"
            )

    @staticmethod
    def haversine_miles(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
        """
        Computes great-circle distance in miles between two latitude/longitude points.
        """
        r = 3958.8  # Earth radius in miles

        lat1_rad, lon1_rad = math.radians(lat1), math.radians(lon1)
        lat2_rad, lon2_rad = math.radians(lat2), math.radians(lon2)

        dlat = lat2_rad - lat1_rad
        dlon = lon2_rad - lon1_rad

        a = (
            math.sin(dlat / 2) ** 2
            + math.cos(lat1_rad) * math.cos(lat2_rad) * math.sin(dlon / 2) ** 2
        )
        c = 2 * math.asin(math.sqrt(a))
        return r * c

    def build_adjacency(self, radius_miles: float | None = None) -> np.ndarray:
        """
        Builds the coverage adjacency matrix A.

        A[i, j] = 1 means city i can cover city j
        A[i, j] = 0 means city i cannot cover city j

        A city always covers itself.
        """
        radius = radius_miles if radius_miles is not None else self.config.radius_miles
        adjacency = np.zeros((self.n, self.n), dtype=int)

        for i in range(self.n):
            for j in range(self.n):
                dist = self.haversine_miles(
                    self.latitudes[i], self.longitudes[i],
                    self.latitudes[j], self.longitudes[j]
                )
                if dist <= radius:
                    adjacency[i, j] = 1

        return adjacency

    def _threshold_candidates(self, pop_threshold: int, theta_threshold: int) -> list[int]:
        """
        Filters the full city list down to candidate cities V3.

        A city becomes a candidate if:
        - its population indicator sum >= pop_threshold
        - its economic indicator sum >= theta_threshold
        """
        if self.phi_cols:
            pop_sum = self.df[self.phi_cols].sum(axis=1).astype(int).to_numpy()
        else:
            pop_sum = np.zeros(self.n, dtype=int)

        if self.theta_cols:
            theta_sum = self.df[self.theta_cols].sum(axis=1).astype(int).to_numpy()
        else:
            theta_sum = np.zeros(self.n, dtype=int)

        pop_ok = pop_sum >= pop_threshold
        theta_ok = theta_sum >= theta_threshold

        return [i for i in range(self.n) if pop_ok[i] and theta_ok[i]]

    def solve(
        self,
        pop_threshold: int,
        theta_threshold: int,
        radius_miles: float | None = None,
        global_budget: float | None = None,
    ) -> dict:
        """
        Solves the constrained minimum dominating set model.

        Objective:
            Minimize number of selected cities

        Subject to:
            1. Every city must be covered by at least one selected candidate city
            2. Total selected cost must stay within budget
            3. Any optional separation-pair rules must be respected
        """
        radius = radius_miles if radius_miles is not None else self.config.radius_miles
        candidates = self._threshold_candidates(pop_threshold, theta_threshold)

        result = {
            "pop_threshold": pop_threshold,
            "theta_threshold": theta_threshold,
            "radius_miles": radius,
            "num_candidates": len(candidates),
        }

        if not candidates:
            result.update({
                "status": "no_candidates",
                "selected_indices": [],
                "selected_ids": [],
                "num_selected": 0,
                "total_cost": None,
            })
            return result

        adjacency = self.build_adjacency(radius)

        if global_budget is None:
            candidate_cost_sum = float(sum(self.costs[i] for i in candidates))
            global_budget = self.config.global_budget_factor * candidate_cost_sum

        # Step 1: feasibility check
        # Before sending anything to Gurobi, verify that every city has at least
        # one candidate city that could cover it.
        for j in range(self.n):
            coverers = [i for i in candidates if adjacency[i, j] == 1]
            if not coverers:
                result.update({
                    "status": "cover_impossible",
                    "selected_indices": [],
                    "selected_ids": [],
                    "num_selected": 0,
                    "total_cost": None,
                })
                return result

        # Step 2: build model
        model = gp.Model("nfl_expansion")
        model.setParam("OutputFlag", 0)
        model.setParam("MIPGap", self.config.mip_gap)
        if self.config.time_limit is not None:
            model.setParam("TimeLimit", int(self.config.time_limit))

        # Binary decision variable:
        # x[i] = 1 if candidate city i is selected
        x = {
            i: model.addVar(vtype=GRB.BINARY, name=f"x_{i}_{self.city_ids[i]}")
            for i in candidates
        }

        model.update()

        # Step 3: objective
        # Minimize the number of selected expansion cities
        model.setObjective(gp.quicksum(x[i] for i in candidates), GRB.MINIMIZE)

        # Step 4: coverage constraints
        # Every city j must be covered by at least one selected candidate city i
        for j in range(self.n):
            coverers = [i for i in candidates if adjacency[i, j] == 1]
            model.addConstr(
                gp.quicksum(x[i] for i in coverers) >= 1,
                name=f"coverage_{j}"
            )

        # Step 5: budget constraint
        model.addConstr(
            gp.quicksum(self.costs[i] * x[i] for i in candidates) <= global_budget,
            name="budget"
        )

        # Step 6: optional separation constraints
        # These prevent specific city pairs from both being selected.
        separation_pairs = self.config.separation_pairs or []
        for i, k in separation_pairs:
            if i in x and k in x:
                model.addConstr(x[i] + x[k] <= 1, name=f"separation_{i}_{k}")

        # Step 7: solve
        model.optimize()

        if model.Status in (GRB.OPTIMAL, GRB.TIME_LIMIT, GRB.SUBOPTIMAL):
            selected_indices = [i for i in candidates if x[i].X > 0.5]
            selected_ids = [self.city_ids[i] for i in selected_indices]
            total_cost = float(sum(self.costs[i] for i in selected_indices))

            result.update({
                "status": "ok",
                "selected_indices": selected_indices,
                "selected_ids": selected_ids,
                "num_selected": len(selected_indices),
                "total_cost": total_cost,
                "budget_used": total_cost,
                "budget_limit": float(global_budget),
            })
            return result

        result.update({
            "status": f"gurobi_status_{model.Status}",
            "selected_indices": [],
            "selected_ids": [],
            "num_selected": 0,
            "total_cost": None,
        })
        return result

    def sensitivity_sweep(
        self,
        pop_thresholds: Iterable[int],
        theta_thresholds: Iterable[int],
        radius_miles: float | None = None,
        global_budget: float | None = None,
    ) -> pd.DataFrame:
        """
        Runs the model across multiple threshold combinations.

        Returns a tidy DataFrame so you can sort, filter, save, or chart results.
        """
        records: list[dict] = []

        for pop_threshold in pop_thresholds:
            for theta_threshold in theta_thresholds:
                res = self.solve(
                    pop_threshold=pop_threshold,
                    theta_threshold=theta_threshold,
                    radius_miles=radius_miles,
                    global_budget=global_budget,
                )
                records.append({
                    "pop_threshold": res["pop_threshold"],
                    "theta_threshold": res["theta_threshold"],
                    "radius_miles": res["radius_miles"],
                    "num_candidates": res["num_candidates"],
                    "status": res["status"],
                    "num_selected": res["num_selected"],
                    "total_cost": res["total_cost"],
                    "selected_ids": "; ".join(res["selected_ids"]),
                })

        return pd.DataFrame(records)

    @classmethod
    def from_csv(
        cls,
        csv_path: str | Path,
        **kwargs,
    ) -> "NFLExpansionOptimizer":
        """
        Convenience constructor so you can load data directly from a CSV.
        """
        df = pd.read_csv(csv_path)
        return cls(df=df, **kwargs)